version: 2
enable-beta-ecosystems: true
updates:
    - package-ecosystem: npm
      directory: "/"
      schedule:
          interval: daily
      #enable if the we add a label to the repo
      #labels:
      #    - "dependencies"
